### ISSUE TITLE
LoadingActivity问题

### ISSUE THREAD

**Issue by Allen0828** [AriesHoo/UIWidget#52]
使用ProgressDialog 发现延迟关闭是关闭不了的. 很奇怪 在测试代码里添加了 点击空白区域不响应, 就不能关闭了. 很好奇大家在使用的时候 都是怎么关的?  
LoadingActivity -> 94行

```java
 case R.id.rtv_showLoading:
        new UIProgressDialog.NormalBuilder(this)
                 .setMessage(isShowMsg ? R.string.loading : 0)
                 .setIndeterminateDrawable(isDefaultProgress ? 0 : R.drawable.progress_loading)
                 .setBackgroundRadiusResource(isDefaultRadiusBack ? R.dimen.dp_radius_loading : 0)
                 .setCanceledOnTouchOutside(false)  // 新增
                 .create()
                 .setDimAmount(isBackDim ? 0.6f : 0f)
                .show();
      break;
```

**Comment by AriesHoo** [comment]
不太明白你的意思。create()方法会创建dialog然后对这个dialog进行show和dismiss操作就是显示和关闭



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月07日 21:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [AriesHoo/UIWidget] LoadingActivity问题 (Issue #52) |

使用ProgressDialog 发现延迟关闭是关闭不了的. 很奇怪 在测试代码里添加了 点击空白区域不响应, 就不能关闭了. 很好奇大家在使用的时候 都是怎么关的?
LoadingActivity -> 94行

caseR.id.rtv_showLoading:newUIProgressDialog.NormalBuilder(this)

                 .setMessage(isShowMsg ?R.string.loading :0)

                 .setIndeterminateDrawable(isDefaultProgress ?0:R.drawable.progress_loading)

                 .setBackgroundRadiusResource(isDefaultRadiusBack ?R.dimen.dp_radius_loading :0)

                 .setCanceledOnTouchOutside(false)  // 新增

                 .create()

                 .setDimAmount(isBackDim ?0.6f:0f)

                .show();

      break;

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Allen0828** [comment]
就是 我需要在展示Dialog之后  自动关闭. 比如 延迟5秒后关闭. 
但是 现在 使用UIWidget组件, 用户点击空白区域 Dialog会消失.  所以我加了一句  不响应空白区域的代码.
然后 不知道应该怎么关闭了
之前尝试使用了 以下代码  但是关不掉.
刚接触安卓  实在不好意思 😓
```kotlin
val dialog = UIProgressDialog.NormalBuilder(this)
// init代码
// 延迟2秒后自动关闭
Timer().schedule(2000) {
                runOnUiThread {
                    dialog. create().dismiss()
                }
   }
```

**Comment by AriesHoo** [comment]
外面执行create()会返回dialog对象。先show()就显示。延时再调用dismiss()即可发自我的华为手机-------- 原始邮件 --------发件人： "Allen.zhang" ***@***.***>日期： 2021年12月8日周三 20:44收件人： AriesHoo/UIWidget ***@***.***>抄送： Aries Hoo²⁰²¹ ***@***.***>, Comment ***@***.***>主    题： Re: [AriesHoo/UIWidget] LoadingActivity问题 (Issue #52)

就是 我需要在展示Dialog之后  自动关闭. 比如 延迟5秒后关闭.

但是 现在 使用UIWidget组件, 用户点击空白区域 Dialog会消失.  所以我加了一句  不响应空白区域的代码.

然后 不知道应该怎么关闭了

之前尝试使用了 以下代码  但是关不掉.

刚接触安卓  实在不好意思 😓

val dialog = UIProgressDialog.NormalBuilder(this)

// init代码

// 延迟2秒后自动关闭

Timer().schedule(2000) {

                runOnUiThread {

                    dialog. create().dismiss()

                }

   }

**Comment by AriesHoo** [comment]
调用一次create()就会返回一个Dialog 对象。show()和dismiss()要针对同一个Dialog对象。不能show()是dialog A 然后dismiss() dialog B
